name: videocall
description: "A Flutter package for video calling screens."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the Cupertino Icons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0
  cloud_firestore: ^6.1.0
  agora_rtc_engine: ^6.5.3
  permission_handler: ^12.0.1
  http: ^1.6.0
  firebase_messaging: ^16.0.4
  auth:
    path: ../auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
