name: intern_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.17.5
  firebase_database: ^10.5.0
  firebase_storage: ^11.7.0
  firebase_messaging: ^14.9.4
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  dartz: ^0.10.1
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  camera: ^0.11.2
  permission_handler: ^11.3.0
  equatable: ^2.0.5
  http: ^1.1.0
  intl: ^0.19.0

  auth: 
    path: packages/auth
  livestream:
    path: packages/livestream
  chat:
    path: packages/chat
  core:
    path: packages/core
  core_ui:
    path: packages/core_ui
  map_tiler:
    path: packages/map_tiler
  videocall:
    path: packages/videocall
  uploads:
    path: packages/uploads
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
